"use client";
import * as React from "react";
import Link from "next/link";
import { Check, MoreHorizontal, Plus, Users } from "lucide-react";
import { AppLayout } from "@/components/layout/app-layout";
import { SignalCard } from "@/components/signals/signal-card";
import { type DemoFrequency, demoSignals } from "@/lib/demo-data";

export function FrequencyDetail({frequency,canEdit=false}:{frequency:DemoFrequency;canEdit?:boolean}) { const [following,setFollowing]=React.useState(false); const [tab,setTab]=React.useState("Signals"); const signals=demoSignals.filter((item)=>item.frequency?.id===frequency.id); return <AppLayout>
  <div className="mb-7 overflow-hidden rounded-xl border border-white/[.07] bg-white/[.015]"><div className="h-36 bg-[radial-gradient(circle_at_25%_50%,rgba(139,120,220,.18),transparent_30%),linear-gradient(135deg,#12131a,#090a0e)]" /><div className="px-6 pb-6"><div className="-mt-4 mb-5 h-8 w-8 rounded-full border-4 border-[#0b0c10]" style={{background:frequency.color}} /><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 font-mono text-[9px] uppercase tracking-wider text-zinc-600">Frequency</p><h1 className="font-mono text-2xl text-zinc-100">{frequency.name}</h1><p className="mt-3 max-w-xl font-mono text-[11px] leading-5 text-zinc-500">{frequency.description}</p><p className="mt-4 font-mono text-[9px] text-zinc-600">{frequency.signalCount} signals · {frequency.followerCount} followers · by {frequency.owner.username}</p></div><div className="flex gap-2">{!canEdit&&<button onClick={()=>setFollowing(!following)} className="h-10 rounded-lg bg-violet-400/[.12] px-4 font-mono text-[10px] text-violet-300">{following?<Check className="mr-2 inline h-3.5 w-3.5"/>:<Plus className="mr-2 inline h-3.5 w-3.5"/>}{following?"Following":"Follow"}</button>}{canEdit&&<Link href={`/frequencies/${frequency.id}/edit`} aria-label="Edit frequency" className="grid h-10 w-10 place-items-center rounded-lg border border-white/[.08] text-zinc-500"><MoreHorizontal className="h-4 w-4"/></Link>}</div></div></div></div>
  <div className="mb-6 flex gap-6 border-b border-white/[.06]">{["Signals","About","Activity","Trails"].map((item)=><button key={item} onClick={()=>setTab(item)} className={`border-b py-3 font-mono text-[10px] ${tab===item?"border-violet-400 text-zinc-200":"border-transparent text-zinc-600"}`}>{item}</button>)}</div>
  {tab==="Signals" && (signals.length?<div className="columns-1 gap-4 sm:columns-2 xl:columns-3">{signals.map((item)=><SignalCard key={item.id} signal={item}/>)}</div>:<Empty text="No signals have been tuned to this frequency yet."/>)}
  {tab==="About"&&<section className="grid gap-4 sm:grid-cols-2"><Box title="About" text={frequency.description}/><Box title="Tags" text={frequency.tags.map(tag=>`#${tag}`).join("  ")}/><Box title="Collaborators" text="hela · test" icon={<Users className="h-4 w-4"/>}/><Box title="Visibility" text="Public · anyone can follow"/></section>}
  {tab==="Activity"&&<section className="space-y-3">{["test added Clean login flow","hela reordered the frequency","test followed this frequency"].map((item,i)=><div key={item} className="rounded-lg border border-white/[.06] p-4 font-mono text-[10px] text-zinc-400">{item}<span className="float-right text-zinc-700">{i+1}h</span></div>)}</section>}
  {tab==="Trails"&&<Link href="/trails/oauth-login" className="block rounded-xl border border-white/[.07] p-6 font-mono text-xs text-zinc-300">The login path <span className="mt-2 block text-[10px] text-zinc-600">6 connected signals · shared</span></Link>}
  <section className="mt-12"><h2 className="mb-4 font-mono text-[9px] uppercase tracking-wider text-zinc-600">Related frequencies</h2><div className="grid gap-3 sm:grid-cols-3">{["Beautiful interfaces","Auth research","Web weirdness"].map(item=><Link key={item} href="/frequencies" className="rounded-lg border border-white/[.06] p-4 font-mono text-[11px] text-zinc-400 hover:border-white/10">{item}</Link>)}</div></section>
  </AppLayout>; }
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-white/10 px-5 py-16 text-center font-mono text-xs text-zinc-500">{text}</div>}
function Box({title,text,icon}:{title:string;text:string;icon?:React.ReactNode}){return <section className="rounded-xl border border-white/[.06] p-5"><h3 className="mb-3 flex items-center gap-2 font-mono text-[9px] uppercase tracking-wider text-zinc-600">{icon}{title}</h3><p className="font-mono text-[11px] leading-5 text-zinc-400">{text}</p></section>}
