"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bookmark, ExternalLink, Heart, MessageCircle, Pencil, Send, Share2, Trash2 } from "lucide-react";
import { AppLayout } from "@/components/layout/app-layout";
import { SignalCard } from "@/components/signals/signal-card";
import { type DemoSignal, demoSignals } from "@/lib/demo-data";

export function SignalDetail({ signal, canEdit = false }: { signal: DemoSignal; canEdit?: boolean }) {
  const router = useRouter(); const [comment, setComment] = React.useState(""); const [comments, setComments] = React.useState([{ id: "one", user: "test", body: "The kind of fragment that changes how you notice the next interface.", time: "18m" }, { id: "two", user: "hela", body: "Saved this to Beautiful interfaces.", time: "42m" }]);
  function addComment(event: React.FormEvent) { event.preventDefault(); if (!comment.trim()) return; setComments([...comments, {id: String(Date.now()), user: "hela", body: comment.trim(), time: "now"}]); setComment(""); }
  async function remove() { if (!window.confirm("Delete this signal?")) return; const response = await fetch(`/api/signals/${signal.id}`, {method: "DELETE"}); if (response.ok || response.status === 401 || response.status === 404) router.push("/archive"); }
  return <AppLayout>
    <Link href="/discover" className="mb-6 inline-flex items-center gap-2 font-mono text-[10px] text-zinc-500 hover:text-zinc-200"><ArrowLeft className="h-3.5 w-3.5" />Back to archive</Link>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_280px]">
      <div><SignalCard signal={signal} variant="featured" /><section id="comments" className="mt-8 rounded-xl border border-white/[.07] bg-white/[.015] p-5"><div className="mb-5 flex items-center gap-2"><MessageCircle className="h-4 w-4 text-violet-300" /><h2 className="font-mono text-sm">Conversation</h2><span className="font-mono text-[10px] text-zinc-600">{comments.length}</span></div><form onSubmit={addComment} className="mb-6 flex gap-2"><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Add to the conversation..." className="h-11 flex-1 rounded-lg border border-white/[.08] bg-[#0a0b10] px-3 font-mono text-xs outline-none focus:border-violet-400/30" /><button className="grid h-11 w-11 place-items-center rounded-lg bg-violet-400/[.12] text-violet-300" aria-label="Post comment"><Send className="h-4 w-4" /></button></form><div className="space-y-5">{comments.map((item) => <article key={item.id} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[.03] font-mono text-[10px] text-zinc-400">{item.user[0]}</span><div><p className="font-mono text-[10px] text-zinc-400">{item.user} <span className="text-zinc-700">· {item.time}</span></p><p className="mt-1.5 font-mono text-[11px] leading-5 text-zinc-300">{item.body}</p><button className="mt-2 font-mono text-[9px] text-zinc-600 hover:text-violet-300">Reply</button></div></article>)}</div></section></div>
      <aside className="space-y-4"><section className="rounded-xl border border-white/[.07] bg-white/[.015] p-5"><p className="font-mono text-[9px] uppercase tracking-wider text-zinc-600">Signal details</p><dl className="mt-5 space-y-4 font-mono text-[10px]"><Row label="Strength" value={`${signal.signalStrength}%`} /><Row label="Saved" value={String(signal.saveCount)} /><Row label="Reactions" value={String(signal.reactionCount)} /><Row label="Visibility" value={signal.visibility.toLowerCase()} /><Row label="Frequency" value={signal.frequency?.name || "Unsorted"} /></dl></section><div className="grid grid-cols-2 gap-2"><Action icon={Heart} label="React" /><Action icon={Bookmark} label="Save" /><Action icon={Share2} label="Share" onClick={() => navigator.clipboard.writeText(location.href)} />{signal.sourceUrl ? <a href={signal.sourceUrl} target="_blank" rel="noreferrer" className="flex h-10 items-center justify-center gap-2 rounded-lg border border-white/[.07] font-mono text-[10px] text-zinc-500 hover:text-zinc-200"><ExternalLink className="h-3.5 w-3.5" />Source</a> : <Action icon={ExternalLink} label="Open" />}</div>{canEdit&&<><Link href={`/signals/${signal.id}/edit`} className="flex h-10 items-center justify-center gap-2 rounded-lg border border-white/[.07] font-mono text-[10px] text-zinc-500 hover:text-zinc-200"><Pencil className="h-3.5 w-3.5" />Edit signal</Link><button onClick={remove} className="flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-red-400/10 font-mono text-[10px] text-red-400/60 hover:bg-red-400/[.04]"><Trash2 className="h-3.5 w-3.5" />Delete signal</button></>}</aside>
    </div>
    <section className="mt-12"><h2 className="mb-5 font-mono text-[10px] uppercase tracking-wider text-zinc-500">Related signals</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{demoSignals.filter((item) => item.id !== signal.id).slice(0,3).map((item) => <SignalCard key={item.id} signal={item} />)}</div></section>
  </AppLayout>;
}
function Row({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4"><dt className="text-zinc-600">{label}</dt><dd className="truncate text-zinc-300">{value}</dd></div>; }
function Action({icon:Icon,label,onClick}:{icon:React.ElementType;label:string;onClick?:()=>void}) { const [active,setActive]=React.useState(false); return <button onClick={() => {setActive(!active); onClick?.();}} className={`flex h-10 items-center justify-center gap-2 rounded-lg border border-white/[.07] font-mono text-[10px] hover:bg-white/[.03] ${active ? "text-violet-300" : "text-zinc-500"}`}><Icon className={`h-3.5 w-3.5 ${active ? "fill-current" : ""}`} />{active ? "Done" : label}</button>; }
