"use client";
import * as React from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { Check, Search, UserPlus } from "lucide-react";
import { AppLayout } from "@/components/layout/app-layout";
import { PageHeading } from "@/components/page-heading";
import { demoUsers } from "@/lib/demo-data";
export default function PeoplePage(){const {data:session}=useSession();const [q,setQ]=React.useState("");const [following,setFollowing]=React.useState<string[]>([]);const [blocked,setBlocked]=React.useState<string[]>([]);const users=demoUsers.filter(u=>u.username!==session?.user?.username&&(u.username+u.bio).toLowerCase().includes(q.toLowerCase()));return <AppLayout><PageHeading eyebrow="People" title="People who notice things" description="Follow collectors whose taste makes your archive more interesting."/><div className="relative mb-6"><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-600"/><input value={q} onChange={e=>setQ(e.target.value)} className="h-10 w-full rounded-lg border border-white/[.07] bg-white/[.02] pl-10 font-mono text-xs outline-none" placeholder="Search people..."/></div><div className="grid gap-4 sm:grid-cols-2">{users.map(user=><article key={user.id} className="rounded-xl border border-white/[.07] bg-white/[.015] p-5"><div className="flex gap-4"><Link href={`/profile/${user.username}`}><img src={user.avatarUrl} alt="" className="h-14 w-14 rounded-full border border-white/10 bg-zinc-900 grayscale"/></Link><div className="min-w-0 flex-1"><Link href={`/profile/${user.username}`} className="font-mono text-sm text-zinc-200">{user.username}</Link><p className="mt-2 line-clamp-2 font-mono text-[10px] leading-5 text-zinc-600">{user.bio}</p></div></div><div className="mt-5 flex gap-2"><button disabled={blocked.includes(user.id)} onClick={()=>setFollowing(list=>list.includes(user.id)?list.filter(id=>id!==user.id):[...list,user.id])} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg bg-violet-400/[.1] font-mono text-[10px] text-violet-300 disabled:opacity-30">{following.includes(user.id)?<Check className="h-3.5 w-3.5"/>:<UserPlus className="h-3.5 w-3.5"/>}{following.includes(user.id)?"Following":"Follow"}</button><button onClick={()=>setBlocked(list=>list.includes(user.id)?list.filter(id=>id!==user.id):[...list,user.id])} className="h-9 rounded-lg border border-white/[.07] px-3 font-mono text-[9px] text-zinc-600">{blocked.includes(user.id)?"Unblock":"Block"}</button><button onClick={()=>alert(`Report for @${user.username} submitted for review.`)} className="h-9 rounded-lg border border-white/[.07] px-3 font-mono text-[9px] text-zinc-600">Report</button></div></article>)}</div></AppLayout>}
